version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 690050948477.dkr.ecr.us-east-1.amazonaws.com
      - export IMAGE_URI=690050948477.dkr.ecr.us-east-1.amazonaws.com/aws-blog-images:$CODEBUILD_BUILD_NUMBER

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $IMAGE_URI
      - echo "{\"name\":\"backend\",\"imageUri\":\"$IMAGE_URI\"}" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
