version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 690050948477.dkr.ecr.us-east-1.amazonaws.com
      - export FRONTEND_IMAGE=690050948477.dkr.ecr.us-east-1.amazonaws.com/blog-website-frontend:$CODEBUILD_BUILD_NUMBER
      - export BACKEND_IMAGE=690050948477.dkr.ecr.us-east-1.amazonaws.com/blog-website-backend:$CODEBUILD_BUILD_NUMBER

  build:
    commands:
      - echo Building Docker images...
      - docker-compose build
      - docker tag blogging-website_frontend $FRONTEND_IMAGE
      - docker tag blogging-website_backend $BACKEND_IMAGE

  post_build:
    commands:
      - echo Pushing images to Amazon ECR...
      - docker push $FRONTEND_IMAGE
      - docker push $BACKEND_IMAGE
      - echo Creating imagedefinitions.json for ECS...
      - printf '[{"name":"frontend","imageUri":"%s"},{"name":"backend","imageUri":"%s"}]' $FRONTEND_IMAGE $BACKEND_IMAGE > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
