version: "3.8"

services:
  backend:
    image: suleman43/blog-website-backend:latest
    container_name: backend
    ports:
      - "5001:5000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:5000/api/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  frontend:
    image: suleman43/blog-website-frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=http://backend:5000
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

networks:
  app-network:
    driver: bridge
    name: blog-app-network # Explicit network naming
