version: "3.8"
services:
  backend:
    image: suleman43/blog-website-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: suleman43/blog-website-frontend:latest
    container_name: frontend
    ports:
      - "80:5173"
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=http://backend:5000
      - HOST=0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
