version: "3.8"
services:
  backend:
    build:
      context: ./backend
    image: blogging-website_backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: blogging-website_frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=http://backend:5000
      - HOST=0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
